                                                                                                                                                                                                                                                                                                                                                                   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectochat81;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author sala-406
 */
public class FrmUsuario1 extends javax.swing.JFrame implements Observer  {

    /**
     * Creates new form FrmUsuario1
     */
    public FrmUsuario1() {
        initComponents();
        this.setTitle("Usuario Principal");
        //Atento al uso del boton enviar
        this.getRootPane().setDefaultButton(jBtEnviar1);
        //Define un objeto de la clase servidor y se abre un puerto para conexion.
        Servidor serv = new Servidor(9000);
        //Servidor atento a cualquier notificacion
        serv.addObserver(this);
        Thread t = new Thread (serv);
        t.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaChat1 = new javax.swing.JTextArea();
        jTxMensaje1 = new javax.swing.JTextField();
        jBtEnviar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCbDireccionIp = new javax.swing.JComboBox<>();
        jCbPuerto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTaChat1.setEditable(false);
        jTaChat1.setColumns(20);
        jTaChat1.setRows(5);
        jScrollPane1.setViewportView(jTaChat1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 72, 420, 240));
        jPanel1.add(jTxMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 344, 330, -1));

        jBtEnviar1.setText("Enviar");
        jBtEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEnviar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtEnviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 80, -1));

        jLabel1.setText("Enviar a:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 30));

        jCbDireccionIp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "172.20.2.234", "172.20.2.155", "172.20.2.231", "172.20.2.203", "172.20.2.254", "172.16.1.203", "172.20.2.210", "172.16.5.38" }));
        jPanel1.add(jCbDireccionIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jCbPuerto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6000", "6500", "7000", "7500", "8000", "8500", "9000", "9500" }));
        jCbPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbPuertoActionPerformed(evt);
            }
        });
        jPanel1.add(jCbPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, -1));

        jLabel2.setText("Puerto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEnviar1ActionPerformed
        String mensaje = "Juan: " + jTxMensaje1.getText()+"\n";
        String host = (String) jCbDireccionIp.getSelectedItem();
        int puerto = Integer.parseInt(jCbPuerto.getSelectedItem().toString());
        jTaChat1.append(mensaje);
        jTxMensaje1.setText("");
        Cliente clie = new Cliente(host, puerto, mensaje);
        Thread t = new Thread(clie);
        t.start();
    }//GEN-LAST:event_jBtEnviar1ActionPerformed

    private void jCbPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbPuertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEnviar1;
    private javax.swing.JComboBox<String> jCbDireccionIp;
    private javax.swing.JComboBox<String> jCbPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTaChat1;
    private javax.swing.JTextField jTxMensaje1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
       jTaChat1.append((String)arg);
       
   }
}
